<?php

namespace Daun\StatamicAssetThumbnails\Commands;

use Daun\StatamicAssetThumbnails\Services\ThumbnailService;
use Illuminate\Console\Command;
use Statamic\Console\RunsInPlease;

class ClearCommand extends Command
{
    use RunsInPlease;

    protected $signature = 'thumbnails:clear';

    protected $description = 'Remove all autogenerated asset thumbnails';

    public function handle(ThumbnailService $service): void
    {
        $count = $service->removeAll();

        $this->info(sprintf('Cleared thumbnails for %d assets', $count));
    }
}
