name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.3, 8.2]
        laravel: [12.*, 11.*]
        statamic: [6.*]
        include:
          - laravel: 12.*
            testbench: 10.*
            pest: 3.*
          - laravel: 11.*
            testbench: 9.*
            pest: 3.*
        exclude:
          - laravel: 12.*
            php: 8.1
          - laravel: 11.*
            php: 8.1
    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }} / Statamic ${{ matrix.statamic }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "statamic/cms:${{ matrix.statamic }}" "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.pest }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: composer run lint

      - name: Execute tests
        run: composer run test:ci

      - name: Check code coverage
        uses: codecov/codecov-action@v4
        if: ${{ matrix.php == '8.4' && matrix.laravel == '12.*' }}
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
